---
name: General repository validation
on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: GH - repository checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: GCP - authenticate
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIP }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          # token_format: "access_token"

      - name: GCP - setup SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: GCP - access verification
        run: gcloud storage buckets list

      - name: TF - setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: TF - version
        run: terraform version

      - name: TF - configure backend
        run: |
          cat <<EOF >backend.tf
          terraform {
            backend "gcs" {
              bucket  = ${{ secrets.TF_BACKEND_BUCKET }}
            }
          }
          EOF
        working-directory: project/dev/

      # - name: TF - initialize configuration
      #   run: terraform init
      #   working-directory: project/dev/

      # - name: TF - validate configuration
      #   run: terraform validate
      #   working-directory: project/dev/

      # - name: TF - state list existing
      #   run: terraform state list || echo "No existing state"
      #   working-directory: project/dev/

      # - name: TF - plan execution
      #   run: terraform plan -out=tfplan
      #   working-directory: project/dev/
